server:
  port: 8082
  mode: "dev"

mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "123456"
  db_name: "boxfetch"
  max_open_conns: 100
  max_idle_conns: 10
  conn_max_lifetime: 14400

log:
  log_level: "debug"
  file_log_name: "./storages/logs/dev.001.log"
  max_size: 500
  max_backups: 3
  max_age: 28
  compress: true

redis:
  addr: "127.0.0.1:6379"   # Redis container name in the Docker network
  password: "123456"  # Password for Redis if you set it in the docker-compose.yml
  db: 0                   # Default Redis DB
  pool_size: 10           # Redis connection pool size
  min_idle_conns: 5       # Minimum idle connections in the pool
  dial_timeout: 5         # Dial timeout in seconds
  read_timeout: 3         # Read timeout in seconds
  write_timeout: 3        # Write timeout in seconds


kafka:
  brokers:
    - "localhost:9092"
  client_id: "your-client-id"
  topic: "your-topic"
  acks: "all"


security:
  jwt:
    key: "super-secret-key"

databases:
  - user: "admin"
    host: "localhost"
    db_name: "testdb"
